title: "PHPによるFWを用いたアプリケーション開発再入門 w/CakePHP4"
summary: |-
  いわゆるMVCフレームワーク(FW)を用いたアプリケーション開発経験者向けに、「最近の事情」を加味した開発の勘所をつまみ喰いするための再入門です。

  FW上にアプリケーションを構築することができて、PHPも苦労なく読み書きできている・・・一方で、(何らかの事情により?)最近の書き方やよく見かける仕組みについては分かっていない！！といった人たちが、今日のFWや作り方に影響を与えている要因などにも目を向けながら、FWを用いたアプリケーション開発に”再”入門できることが本書の狙いです。
  題材としてはCakePHPを利用します。公式チュートリアルを独力で難なくこなせるようなレベルを想定し、「ただ表面的にFW(CakePHP)を使うだけなら無くても良いが、知っておくことで本質的な理解を助けてくれそうな話」を展開していきます。

topics: ["PHP", "CakePHP", "PSR"]
published: false
price: 500
toc_depth: 2
chapters:
  - 0-1_introduction
  - 1-1_setup-dev-env
  - 1-2_hello-cakephp
  - 1-3_psr4-with-cakephp
  - 1-4_about-composer
  - C-1_about-psr-and-phpfig
  - 2-1_psr7-with-cakephp
  - 2-2_psr15-with-cakephp
  - 2-3_psr11-with-cakephp
  - C-2_psr-in-cakephp
  - 3-1_cake-orm
  - 3-2_cake-console
  - 3-3_logs
  - C-3_cakephp-repository-strategy
  - 4-1_phpunit-with-cakephp
  - 4-2_qatools-with-cakephp
  - C-4_fixture-patterns
  - 5-1_latest-php-feature
  - 5-2_developer-tools-in-or-with-cakephp
  - C-5_to-up-to-date-continuously
  - auth
  - plugins
  - security
  - view
