title: "[WIP]XdebugとPhpStormを使って「難しめ」なコードを読んでみよう！"
summary: |-
  PHPで作成されたソフトウェアの、ソースコードを読んでみましょう！
  OSSプロジェクトのコードを例にとって、チュートリアル仕立てで実際にコードの読解を進めていきます。
  実例を通じてツールの操作や思考を追体験することで、PhpStormとXdebugの基本的な活用方法が身につくことでしょう。
  新しいプロジェクトでコードに触れる際や、自身が管理するものよりも複雑なものに挑む助けとなる──そんな味方が、ここに居ますよ

topics: ["PHP", "PhpStorm", "Xdebug"]
published: true
price: 0
# 本に含めるチャプターを順番に並べましょう
chapters:
  - x_intro
  - 0-1_setup
  - 1-0_cover
  - 1-1_about-xdebug
  - 1-2_hello-step
  - 1-3_step-basic
  - 2-0_cover
  - 2-1_run-test
  - 2-2_hello-break
  - 2-3_reading-phpunit
